[book]
authors = ["Phodal Huang"]
language = "en"
multilingual = false
src = "src"
title = "Feakin"
git-repository-url = "https://github.com/feakin/book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/feakin/book/edit/master/{path}"
site-url = "/"
cname = "book.feakin.com"
