[book]
authors = ["Feakin Team"]
language = "en"
multilingual = false
src = "src"
title = "Feakin - 软件开发工业化 DSL"

[output.html]
git-repository-url = "https://github.com/feakin/book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/feakin/book/edit/master/{path}"
site-url = "/"
cname = "book.feakin.com"
additional-js = ["assets/custom.js"]
